version: '3.3'
services:
  "db":
    "image": "postgres:latest"
    "ports":
      - "5432:5432"
    "environment":
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=mydb"
      - "POSTGRES_URL=postgresql://postgres:mysecretpassword@localhost:5432/mydb"
    "volumes":
      - "./data:/var/lib/postgresql/data"
    "networks":
        - "default"